### ISSUE TITLE
ValueError when training model with 'Brand' predictor

### ISSUE THREAD

**Issue by AnthonyBebek** [pinbal-wizard/ST1-Assignment-3---Capstone#1]
# Expected Behavior

The model should train successfully and output MAPE values without errors.

# Current Behavior

Currently, when 'Brand' is selected as a predictor, the script throws a ```ValueError``` during model training: ```could not convert string to float.```

# Failure Information

The issue likely happens because ```Brand``` is stored as a categorical datatype. The model expects a float input. Leading to the conversion error. We did use one-hot encoding to fix this but the datatype was changed back in the lastest version to help make EDA easier for the user.

This issue has only been tested on the brand but I believe it will also happen on the other categorical datatypes.

## Steps to Reproduce

1. Select 'Brand' as one of the final predictors
2. Train with any regression algorithm and any data split
3. The script throws a ValueError when it attempts to convert the entire ```brand``` column to a float.

![image](https://github.com/user-attachments/assets/b2e89a17-b521-4ff5-9419-92b8e66b99b0)

## Context
* Software Version: Latest (python 3.12.3)

**Comment by ThomSpencer** [comment]
bug is not present if using XGBoost as your algorithm

**Comment by AnthonyBebek** [comment]
Issue has been fixed, the Liner, Decision Tree, Random forest, Adaboost, K-Nearest neighbor and SVR algorithms have been fixed to accept this new datatype
