### ISSUE TITLE
ValueError when training with "Kilometres" as predictors

### ISSUE THREAD

**Issue by WalkieCat** [pinbal-wizard/ST1-Assignment-3---Capstone#2]
# Expected
Run smoothly without trouble

# Reality and some information on Bug
Program explodes, due to NaN values present in this columns

## Steps to reproduce
1. Pick "Delete Rows" as the cleaning mode
2. Pick "Kilometres" as one of the predictors
3. Watch it explodes
4. If any other mode is picked, program crash
![image](https://github.com/user-attachments/assets/2e564645-50b7-4d80-af8e-0fa5fe3a835d)

This is when picking any other cleaning mode:
![image](https://github.com/user-attachments/assets/3416c086-ff37-4cc5-9983-fddc1dca829f)
![image](https://github.com/user-attachments/assets/5e4c30ed-d0e7-49df-96b4-2fbbd016fdb1)

**Comment by AnthonyBebek** [comment]
Added a hotfix to this problem by removing null values for the kilometers column after it attempts to replace them with the mode value for that column. This issue only happened when the data was cleaned using the ```Mode``` mode. Will look into this further, but for now, the code now runs, however the values might be skewed slightly.

**Comment by WalkieCat** [comment]
Issue resolved
